#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-junit5
Version  : 5.4.0
Release  : 3
URL      : https://github.com/junit-team/junit5/archive/r5.4.0.tar.gz
Source0  : https://github.com/junit-team/junit5/archive/r5.4.0.tar.gz
Source1  : https://repo1.maven.org/maven2/org/junit/junit-bom/5.4.0/junit-bom-5.4.0.pom
Source2  : https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.1.0/junit-jupiter-api-5.1.0.jar
Source3  : https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.1.0/junit-jupiter-api-5.1.0.pom
Source4  : https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter/5.5.1/junit-jupiter-5.5.1.jar
Source5  : https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter/5.5.1/junit-jupiter-5.5.1.pom
Source6  : https://repo1.maven.org/maven2/org/junit/platform/junit-platform-commons/1.1.0/junit-platform-commons-1.1.0.jar
Source7  : https://repo1.maven.org/maven2/org/junit/platform/junit-platform-commons/1.1.0/junit-platform-commons-1.1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 EPL-2.0
Requires: mvn-junit5-data = %{version}-%{release}
Requires: mvn-junit5-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
# JUnit 5
This repository is the home of the next generation of JUnit, _JUnit 5_.

%package data
Summary: data components for the mvn-junit5 package.
Group: Data

%description data
data components for the mvn-junit5 package.


%package license
Summary: license components for the mvn-junit5 package.
Group: Default

%description license
license components for the mvn-junit5 package.


%prep
%setup -q -n junit5-r5.4.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-junit5
cp LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-junit5/LICENSE.md
cp junit-jupiter-params/LICENSE-univocity-parsers.md %{buildroot}/usr/share/package-licenses/mvn-junit5/junit-jupiter-params_LICENSE-univocity-parsers.md
cp junit-platform-console/LICENSE-picocli.md %{buildroot}/usr/share/package-licenses/mvn-junit5/junit-platform-console_LICENSE-picocli.md
cp junit-platform-testkit/LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-junit5/junit-platform-testkit_LICENSE.md
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/junit/junit-bom/5.4.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/junit/junit-bom/5.4.0/junit-bom-5.4.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.1.0/junit-jupiter-api-5.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.1.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.1.0/junit-jupiter-api-5.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter/5.5.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter/5.5.1/junit-jupiter-5.5.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter/5.5.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter/5.5.1/junit-jupiter-5.5.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/junit/platform/junit-platform-commons/1.1.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/junit/platform/junit-platform-commons/1.1.0/junit-platform-commons-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/junit/platform/junit-platform-commons/1.1.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/junit/platform/junit-platform-commons/1.1.0/junit-platform-commons-1.1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/junit/junit-bom/5.4.0/junit-bom-5.4.0.pom
/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.1.0/junit-jupiter-api-5.1.0.jar
/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.1.0/junit-jupiter-api-5.1.0.pom
/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter/5.5.1/junit-jupiter-5.5.1.jar
/usr/share/java/.m2/repository/org/junit/jupiter/junit-jupiter/5.5.1/junit-jupiter-5.5.1.pom
/usr/share/java/.m2/repository/org/junit/platform/junit-platform-commons/1.1.0/junit-platform-commons-1.1.0.jar
/usr/share/java/.m2/repository/org/junit/platform/junit-platform-commons/1.1.0/junit-platform-commons-1.1.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-junit5/LICENSE.md
/usr/share/package-licenses/mvn-junit5/junit-jupiter-params_LICENSE-univocity-parsers.md
/usr/share/package-licenses/mvn-junit5/junit-platform-console_LICENSE-picocli.md
/usr/share/package-licenses/mvn-junit5/junit-platform-testkit_LICENSE.md
